<a href="https://colab.research.google.com/github/Krishishah7/nlp-learning-series/blob/main/06_llm_and_fine_tuning/05_llm_evaluation/llm_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U transformers sentencepiece scikit-learn --quiet

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

In [ ]:
prompt = "Explain why exercise is good for health in two sentences."

In [7]:
responses = []

for _ in range(5):
    inputs = tokenizer(prompt, return_tensors="pt")

    outputs = model.generate(
        **inputs,
        max_new_tokens=60,
        temperature=0.9,
        do_sample=True
    )

    text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    responses.append(text)

print("MODEL RESPONSES:\n")

for i, r in enumerate(responses, 1):
    print(f"Response {i}: {r}\n")

MODEL RESPONSES:

Response 1: exercise is good for overall health by lowering blood pressure.

Response 2: They help with heart rate

Response 3: exercise is the key to keeping your body healthy and strong

Response 4: exercise can be good for your overall health

Response 5: exercise burns calories



In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(responses)

similarity_matrix = cosine_similarity(X)

print("SIMILARITY MATRIX:\n")
print(similarity_matrix)

SIMILARITY MATRIX:

[[1.         0.         0.11345984 0.449709   0.07577075]
 [0.         1.         0.         0.         0.        ]
 [0.11345984 0.         1.         0.13226414 0.06722582]
 [0.449709   0.         0.13226414 1.         0.08832863]
 [0.07577075 0.         0.06722582 0.08832863 1.        ]]


In [9]:
import numpy as np

avg_similarity = (np.sum(similarity_matrix) - len(responses)) / (len(responses)*(len(responses)-1))

print("AVERAGE RESPONSE SIMILARITY:")
print(avg_similarity)

AVERAGE RESPONSE SIMILARITY:
0.0926758180344737
